import fs from 'node:fs';
import path from 'node:path';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);
const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const browser=await chromium.launch({headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[];page.on('pageerror',error=>errors.push(error.message));
const out=path.join(process.cwd(),'reports/qa');
const report={isolated_data:true,synthetic_measurements:true};
const base='http://127.0.0.1:8766';
async function ready(){await page.locator('.canvas-status[data-ready="true"]').waitFor({timeout:120000});}
async function save(label){await page.locator('.modal').getByRole('button',{name:label,exact:true}).click();await Promise.race([page.locator('.modal').waitFor({state:'hidden'}),page.locator('.modal .notice').waitFor().then(async()=>{throw Error(await page.locator('.modal .notice').innerText())})]);}
async function rectangle(x,y){await page.getByRole('button',{name:'Marcar área',exact:true}).click();const box=await page.locator('.pdf-overlay').boundingBox();await page.mouse.move(box.x+box.width*x,box.y+box.height*y);await page.mouse.down();await page.mouse.move(box.x+box.width*(x+.08),box.y+box.height*(y+.035),{steps:6});await page.mouse.up();await page.getByRole('button',{name:'Continuar →',exact:true}).click();}
try{
 await page.goto(base,{waitUntil:'networkidle'});await ready();
 await page.screenshot({path:path.join(out,'montagem-simples-desktop.png'),fullPage:true});
 report.initial_buttons=await page.getByRole('button').count();
 report.management_hidden=await page.getByRole('heading',{name:'Reconhecimento assistido'}).count()===0;
 report.canvas_width=await page.locator('.field-drawing').evaluate(el=>el.getBoundingClientRect().width);
 await page.setViewportSize({width:390,height:844});await page.waitForFunction(()=>document.querySelector('.canvas-status')?.getAttribute('data-ready')==='true'&&document.querySelector('.pdf-surface').getBoundingClientRect().width<=document.querySelector('.pdf-scroll').clientWidth);
 await page.screenshot({path:path.join(out,'montagem-simples-mobile.png'),fullPage:true});
 report.mobile_overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
 await page.setViewportSize({width:1440,height:1000});
 await page.goto(base,{waitUntil:'networkidle'});await ready();
 const projects=await (await page.request.get(base+'/api/projects')).json();const pid=projects[0].id;
 if(projects.length!==1||projects[0].name!=='Teste visual isolado — marcação de campo')throw Error('Recusado: não é o projeto temporário de teste.');
 const state=async()=>await (await page.request.get(`${base}/api/projects/${pid}/state`)).json();
 await rectangle(.26,.36);
 await page.getByLabel('Código da peça',{exact:true}).fill('212-F');
 await page.getByLabel('Onde está esta peça?',{exact:true}).fill('Rack 2 · eixo B/4');
 await page.getByLabel('Referência da verificação em campo',{exact:true}).fill('Fixture de teste visual — não é medição real');
 await page.getByLabel('Conferi esta quantidade no projeto.',{exact:true}).check();
 await page.getByLabel('Usar a etapa Montagem para este registro.',{exact:true}).check();
 await page.getByLabel('Conferi que a marca corresponde à peça nesta posição de montagem.',{exact:true}).check();
 await page.screenshot({path:path.join(out,'montagem-simples-formulario.png'),fullPage:true});
 await save('Salvar marcação');
 let s=await state();
 if(s.instances.length!==1||s.progress_events.length!==1||s.progress_events[0].delta!==1)throw Error('Primeira marcação não contou uma unidade.');
 const firstId=s.instances[0].id;
 if(await page.locator('.pdf-overlay path[fill="var(--sucesso)"]').count()!==1)throw Error('Peça concluída não ficou verde.');
 await rectangle(.38,.36);
 await page.getByLabel('Posição da peça',{exact:true}).selectOption(firstId);
 await page.getByLabel('Referência da verificação em campo',{exact:true}).fill('Outra representação da mesma unidade de teste');
 await page.getByLabel('Conferi que a marca corresponde à peça nesta posição de montagem.',{exact:true}).check();
 await save('Salvar marcação');
 s=await state();if(s.instances.length!==1||s.progress_events.length!==1||s.occurrences.length!==2)throw Error('Duas vistas duplicaram a medição.');
 report.same_unit_two_views_counted_once=true;
 await rectangle(.52,.36);
 await page.getByLabel('Onde está esta peça?',{exact:true}).fill('Rack 2 · eixo B/5');
 await page.getByRole('radio',{name:'Sem conclusão registrada',exact:true}).check();
 await page.getByLabel('Referência da verificação em campo',{exact:true}).fill('Posição de teste ainda sem montagem');
 await page.getByLabel('Conferi que a marca corresponde à peça nesta posição de montagem.',{exact:true}).check();
 await save('Salvar marcação');
 s=await state();if(s.instances.length!==2||s.progress_events.length!==1)throw Error('Área cinza gerou avanço indevido.');
 report.gray_area_has_no_progress=true;
 await page.getByRole('button',{name:'Confirmar montagem',exact:true}).click();
 await page.getByLabel('Referência da verificação em campo',{exact:true}).fill('Conclusão da segunda unidade de teste');
 await save('Salvar montagem');
 s=await state();if(s.progress_events.reduce((n,e)=>n+e.delta,0)!==2)throw Error('Atualização não contou a segunda unidade.');
 report.updated_unit_count=2;
 const coordinates=JSON.stringify(s.geometries.map(g=>g.data));
 await page.getByRole('button',{name:'Visualização',exact:true}).click();
 await page.getByRole('button',{name:'Girar 90°',exact:true}).click();
 await page.getByRole('combobox',{name:'Zoom',exact:true}).selectOption('0.55');await ready();
 await page.screenshot({path:path.join(out,'montagem-simples-marcacoes.png'),fullPage:true});
 await page.reload({waitUntil:'networkidle'});await ready();
 s=await state();if(JSON.stringify(s.geometries.map(g=>g.data))!==coordinates)throw Error('Coordenadas alteradas após zoom/rotação/reabertura.');
 if(await page.locator('.pdf-overlay path[fill="var(--sucesso)"]').count()!==3)throw Error('Cores não persistiram nas três representações.');
 report.colors_persist_after_reload=true;
 const b=await page.locator('.pdf-overlay').boundingBox();
 await page.mouse.click(b.x+b.width*.55,b.y+b.height*.38);
 await page.getByRole('button',{name:'Corrigir montagem',exact:true}).waitFor();
 report.shape_interior_selectable=true;
 await page.getByRole('button',{name:'Gestão e revisão',exact:true}).click();
 await page.getByRole('button',{name:'Revisão',exact:true}).click();
 await page.getByRole('heading',{name:'Reconhecimento assistido',exact:true}).waitFor();
 await page.getByRole('button',{name:'← Voltar à montagem',exact:true}).click();await ready();
 report.management_accessible=true;
 await page.getByRole('button',{name:'Exportar desenho',exact:true}).click();
 const downloading=page.waitForEvent('download');
 await page.getByRole('button',{name:'Gerar e baixar',exact:true}).click();
 const download=await downloading;await download.saveAs(path.join(out,'montagem-simples-teste.zip'));
 report.export_downloaded=download.suggestedFilename();
 report.page_errors=errors;
 if(errors.length||report.mobile_overflow)throw Error(JSON.stringify(report));
 fs.writeFileSync(path.join(out,'montagem-simples-validation.json'),JSON.stringify(report,null,2));
 console.log(JSON.stringify(report,null,2));
}catch(error){await page.screenshot({path:path.join(out,'montagem-simples-falha.png'),fullPage:true});console.error(await page.locator('body').innerText());throw error}finally{await browser.close()}
