import fs from 'node:fs';import path from 'node:path';import {createRequire} from 'node:module';
const require=createRequire(import.meta.url);const {chromium}=require(path.join(process.env.USERPROFILE,'.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'));
const root=process.cwd();const browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1600,height:1100}});const issues=[];page.on('pageerror',e=>issues.push(e.message));
const base='http://127.0.0.1:8766';const result={isolated_data:true,real_pdf:'677-208M.pdf',synthetic_measurement_fixture:true};
async function modalSave(){await page.locator('.modal').getByRole('button',{name:'Salvar',exact:true}).click();await Promise.race([page.locator('.modal').waitFor({state:'hidden'}),page.locator('.toast.error').waitFor().then(async()=>{throw Error(await page.locator('.toast.error').innerText())})]);}
try{
 const request=page.request;let r=await request.post(base+'/api/projects',{data:{name:'Teste de interface isolado · sem homologação'}});if(!r.ok())throw Error(await r.text());const project=await r.json();const pid=project.id;
 const content=fs.readFileSync(path.join(root,'Desenhos/677-208M.pdf'));
 r=await request.post(`${base}/api/projects/${pid}/drawings`,{multipart:{file:{name:'677-208M.pdf',mimeType:'application/pdf',buffer:content},technical_number:'TEST-208',revision:'0',expected_version:'1',request_key:crypto.randomUUID()}});if(!r.ok())throw Error(await r.text());
 for(let attempt=0;attempt<90;attempt++){const s=await (await request.get(`${base}/api/projects/${pid}/state`)).json();if(s.pages.length)break;if(s.jobs.some(j=>j.status==='failed'))throw Error(JSON.stringify(s.jobs));await new Promise(r=>setTimeout(r,1000));}
 await page.goto(base,{waitUntil:'networkidle'});await page.getByRole('button',{name:'Gestão e revisão',exact:true}).click();await page.getByRole('combobox',{name:'Projeto',exact:true}).selectOption(pid);await page.waitForFunction(()=>document.querySelector('.canvas-status')?.textContent.includes('PDF.js ·'),null,{timeout:120000});
 await page.getByRole('button',{name:'Etapas',exact:true}).click();await page.getByLabel('Aprovar configuração (sem soma entre etapas)').check();await page.getByLabel('Motivo / evidência da alteração').fill('Configuração de teste isolado');await modalSave();
 await page.getByRole('button',{name:'+ Código',exact:true}).click();await page.getByLabel('Código',{exact:true}).fill('212-F');await page.getByLabel('Quantidade prevista (vazio = desconhecida)').fill('9');await page.getByLabel('Descrição',{exact:true}).fill('Fixture de teste, não homologação real');await page.getByLabel('Aprovar quantidade para o escopo de medição').check();await page.getByLabel('Motivo / evidência da alteração').fill('Fixture isolada de medição 3/9');await modalSave();
 await page.getByRole('button',{name:/212-F · Fixture/}).click();
 await page.getByRole('button',{name:'Vista',exact:true}).click();let b=await page.locator('.pdf-overlay').boundingBox();
 for(const [x,y]of [[90,80],[330,80],[330,260],[90,260]])await page.mouse.click(b.x+x,b.y+y);
 await page.getByRole('button',{name:'Finalizar área',exact:true}).click();await page.getByLabel('Nome / título').fill('Vista de teste isolado');await page.getByLabel('Tipo de vista').selectOption('section');await page.getByLabel('Título / evidência da vista').fill('Fixture de interação, sem afirmação sobre peça real');await modalSave();
 await page.getByRole('button',{name:'Retângulo',exact:true}).click();b=await page.locator('.pdf-overlay').boundingBox();await page.mouse.move(b.x+130,b.y+140);await page.mouse.down();await page.mouse.move(b.x+230,b.y+180,{steps:6});await page.mouse.up();await page.getByRole('button',{name:'Finalizar área',exact:true}).click();await page.getByLabel('Estado da associação (separado da execução)').selectOption('APROVADA');await page.getByLabel('Motivo / evidência da alteração').fill('Fixture de área manual, não associação física real');await modalSave();
 await page.getByRole('button',{name:'3 · Registrar avanço',exact:true}).click();await page.getByLabel('Saldo agregado final na etapa (não incremento)').fill('3');await page.getByLabel('Motivo / evidência da alteração').fill('Teste isolado de saldo sem localização');await page.getByLabel('Confirmei o alcance e a quantidade deste preview').check();await page.getByRole('button',{name:'Confirmar medição',exact:true}).click();await page.locator('.modal').waitFor({state:'hidden'});
 let state=await (await request.get(`${base}/api/projects/${pid}/state`)).json();if(state.progress_events.length!==1||state.progress_events[0].instance_id!==null||state.progress_events[0].delta!==3||state.instances.length!==0)throw Error('Saldo agregado criou identidade ou contagem indevida.');
 const before=JSON.stringify(state.geometries[0].data);const geometryId=state.geometries[0].id;
 await page.getByRole('button',{name:'↶ Desfazer',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('desfeita'));
 state=await (await request.get(`${base}/api/projects/${pid}/state`)).json();if(!state.geometries[0].data.deleted||state.progress_events.length!==1)throw Error('Desfazer alterou medição.');
 await page.getByRole('button',{name:'↷ Refazer',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.toast')?.textContent.includes('refeita'));
 await page.getByRole('combobox').filter({has:page.locator('option',{hasText:'55%'})}).selectOption('0.55');await page.getByRole('button',{name:'Girar 0°',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.canvas-status')?.textContent.includes('PDF.js ·'));await page.screenshot({path:path.join(root,'reports/qa/fluxo-manual-rotacionado.png'),fullPage:true});
 await page.reload({waitUntil:'networkidle'});await page.locator('.canvas-status[data-ready="true"]').waitFor();
 state=await (await request.get(`${base}/api/projects/${pid}/state`)).json();if(JSON.stringify(state.geometries.find(g=>g.id===geometryId).data)!==before)throw Error('Coordenadas mudaram ao salvar/reabrir/rotacionar.');
 result.geometry_persisted=true;result.aggregate_quantity=3;result.instances_created=0;result.undo_redo_preserved_measurement=true;result.rotation_zoom_preserved_pdf_points=true;result.page_errors=issues;
 fs.writeFileSync(path.join(root,'reports/qa/ui-workflow-validation.json'),JSON.stringify(result,null,2));if(issues.length)throw Error(issues.join('; '));console.log(JSON.stringify(result,null,2));
}catch(error){await page.screenshot({path:path.join(root,'reports/qa/fluxo-manual-falha.png'),fullPage:true});fs.writeFileSync(path.join(root,'reports/qa/ui-workflow-error.txt'),String(error)+'\n'+await page.locator('body').innerText());throw error}finally{await browser.close()}
