import {Row,State} from './api';
type Props={state:State;form:any;change:(key:string,value:any)=>void;today:string};
export default function FieldMarkFields({state:s,form:f,change,today}:Props){
 const piece=s.piece_types.find((p:Row)=>p.id===f.type_id),stage=s.stages.find((p:Row)=>p.id===f.stage_id);
 const units=s.instances.filter((u:Row)=>u.type_id===f.type_id&&u.state==='identified');
 const aggregate=s.progress_events.filter((e:Row)=>e.type_id===f.type_id&&e.stage_id===f.stage_id&&!e.instance_id).reduce((n:number,e:Row)=>n+e.delta,0);
 const selectedBalance=s.progress_events.filter((e:Row)=>e.type_id===f.type_id&&e.stage_id===f.stage_id&&e.instance_id===f.instance_id).reduce((n:number,e:Row)=>n+e.delta,0);
 return <><p className="field-help">Uma marca representa uma peça em uma posição da obra.</p>
  <label className="field"><span>Código da peça</span><input aria-label="Código da peça" required list="field-codes" placeholder="Digite o código, ex.: 212-F" value={f.code||''} onChange={e=>{const code=e.target.value.toUpperCase();const p=s.piece_types.find((p:Row)=>p.code===code);change('code',code);change('type_id',p?.id||'');change('quantity',p?.quantity??'');change('instance_id','');change('approve_quantity',false);change('allocate',false)}}/><datalist id="field-codes">{s.piece_types.filter((p:Row)=>p.category==='structure').map((p:Row)=><option value={p.code} key={p.id}>{p.data.description}</option>)}</datalist></label>
  {f.code&&!piece&&<p className="field-help">Selecione um código existente. Novos códigos ficam em Gestão e revisão.</p>}
  {!!units.length&&<label className="field"><span>Posição da peça</span><select aria-label="Posição da peça" value={f.instance_id} onChange={e=>{change('instance_id',e.target.value);change('allocate',false)}}><option value="">Cadastrar uma nova posição</option>{units.map((u:Row)=><option key={u.id} value={u.id}>{u.data.location}</option>)}</select><small>Se esta peça já foi marcada em outra vista, escolha a mesma posição.</small></label>}
  {!f.instance_id&&<label className="field"><span>Onde está esta peça?</span><input required placeholder="Ex.: Rack 2 · eixo B/4 · nível +6,00" value={f.location||''} onChange={e=>change('location',e.target.value)}/></label>}
  <fieldset className="field-status-choice"><legend>{stage?.name||'Montagem'} desta peça</legend><label className={f.value===1?'chosen':''}><input type="radio" name="field-status" checked={f.value===1} onChange={()=>change('value',1)}/><i style={{background:`var(--${stage?.token||'sucesso'})`}}/>Concluída</label><label className={f.value===0?'chosen':''}><input type="radio" name="field-status" checked={f.value===0} onChange={()=>{change('value',0);change('allocate',false)}}/><i className="unmeasured"/>Sem conclusão registrada</label></fieldset>
  <label className="field"><span>Data da verificação</span><input required type="date" max={today} value={f.effective_at} onChange={e=>change('effective_at',e.target.value)}/></label>
  <label className="field"><span>Referência da verificação em campo</span><input required placeholder="Ex.: Vistoria do turno / boletim 025" value={f.reason||''} onChange={e=>change('reason',e.target.value)}/></label>
  {aggregate>0&&f.value===1&&selectedBalance===0&&<label className="check"><input type="checkbox" checked={f.allocate} onChange={e=>change('allocate',e.target.checked)}/>Esta peça faz parte das {aggregate} já registradas sem posição. Apenas localizar, sem aumentar o total.</label>}
  {piece&&piece.validation!=='APPROVED'&&<div className="field-first-use"><b>Primeiro registro deste código</b><label className="field"><span>Quantidade total prevista de {piece.code}</span><input required type="number" min="1" step="1" value={f.quantity} onChange={e=>{change('quantity',e.target.value);change('approve_quantity',false)}}/></label><label className="check"><input required type="checkbox" checked={f.approve_quantity} onChange={e=>change('approve_quantity',e.target.checked)}/>Conferi esta quantidade no projeto.</label></div>}
  {!stage?.data.approved&&<label className="check"><input required type="checkbox" checked={f.approve_stage} onChange={e=>change('approve_stage',e.target.checked)}/>Usar a etapa {stage?.name} para este registro{stage?.data.dependencies?.length?' (respeitando as etapas anteriores)':''}.</label>}
  <label className="check"><input required type="checkbox" checked={f.confirm_installation} onChange={e=>change('confirm_installation',e.target.checked)}/>Conferi que a marca corresponde à peça nesta posição de montagem.</label>
  <details><summary>Usar uma vista já delimitada</summary><label className="field"><span>Vista do desenho</span><select value={f.view_id||''} onChange={e=>change('view_id',e.target.value)}><option value="">Criar uma região para esta marca</option>{s.views.filter((v:Row)=>v.page_id===f.page_id&&!['typical','reference','table'].includes(v.kind)).map((v:Row)=><option key={v.id} value={v.id}>{v.name}</option>)}</select></label></details>
 </>;
}
