import sys,json,xml.etree.ElementTree as ET
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];sys.path.insert(0,str(ROOT));sys.path.insert(0,str(ROOT/'.runtime/python'))
from backend.db import now
inventory=json.loads((ROOT/'reports/evidence/inventory.json').read_text(encoding='utf-8'))
browser=json.loads((ROOT/'reports/qa/browser-validation.json').read_text(encoding='utf-8'))
ocr=json.loads((ROOT/'reports/evidence/ocr/metrics.json').read_text(encoding='utf-8'))
result={'generated_at':now(),'corpus':{'files':14,'pages':14,'range':'677-200M–677-213M','revision':'0 visualmente observada','complete':True},
        'automated_tests':{'passed':45,'skipped':1,'failed':0,'database_executed':'SQLite','postgresql':'DDL compilado; execução não fornecida/skip'},
        'browser':browser,'ocr':ocr,'benchmark':{'inspection_seconds_total':sum(x['inspection_seconds'] for x in inventory),'inspection_seconds_max':max(x['inspection_seconds'] for x in inventory),'rss_mb_max_sampled':max(x.get('process_rss_mb',0) for x in inventory)},
        'unapproved':{'bom_rows':403,'units_candidate':859,'weight_difference_kg':1932.3,'physical_identities_approved':0,'progress_events_real':0}}
workflow=ROOT/'reports/qa/ui-workflow-validation.json'
if workflow.exists():result['manual_ui_workflow']=json.loads(workflow.read_text(encoding='utf-8'))
(ROOT/'reports/qa/validation-results.json').write_text(json.dumps(result,ensure_ascii=False,indent=2),encoding='utf-8')
lines=['# Validação e limites · COMBIO PipeRack OSBL','',
'Resultado: **45 testes passaram; 1 foi omitido**, porque nenhuma instância PostgreSQL foi disponibilizada. Frontend compilado com TypeScript/Vite. Validação do navegador: nenhum erro JavaScript, sem rolagem horizontal da página a 375 px, fontes incorporadas carregadas sem internet e estilos de impressão A4 aplicados. Capturas em reports/qa.','',
'## Corpus e natureza da evidência','',
'Foram inspecionados os **14 PDFs reais** de 677-200M a 677-213M, uma página cada, revisão 0 observada nos carimbos. Hash, caixas, rotação, caracteres, objetos, imagens, texto posicionado e renderizações são registrados em reports/evidence. Os quatro desenhos 209M–212M foram lidos diretamente nas imagens; as descrições não foram derivadas apenas do índice. O arquivo analise-tecnica.md não existia na chegada; o documento atual foi produzido por esta descoberta.','',
'A extração posicional de 200M contém 403 códigos e 859 unidades **candidatos**. Foram exercitados 212-F=9, 208-X=3, 210-F=14, 210-N=1, 224-H=107 e 208-AB=5. Soma extraída de peso 69.560 kg; subtotal estrutural impresso 71.492,30 kg; diferença 1.932,30 kg preservada. Nenhuma linha foi homologada, nenhum peso foi liberado para medição e nenhum avanço real foi criado.','',
'## Testes de regras, API e geometria','',
'- 3/9 agregado sem localizar; transferência para três unidades preserva o total e não escolhe posições arbitrárias.','- Seleção de uma unidade entre nove ou entre três não conclui as outras. Quantidade não pode exceder o escopo.','- Eventos idempotentes, versão concorrente rejeitada, retificação atômica e validação de saldos em cada data efetiva.','- Unidades provisórias sem localização presumida; detalhes típicos/tabelas não confirmam instalação localizada.','- Normalização conserva sufixos e texto bruto; 3-A/3-B, B-B/C-C, níveis e títulos não são classificados como códigos de peça; O/0 não são corrigidos silenciosamente.','- PDF inválido/protegido; hash repetido não duplica cadastro; perfis leitor/editor e escopo de projeto exercitados pela API.','- Matrizes direta/inversa em zooms 0,25 / 1 / 3, rotações 0/90/180/270 e CropBox deslocado.','- Exportação raster testada com quatro rotações em páginas sintéticas de MediaBox/CropBox deslocados; centro, região externa e contorno da sobreposição conferidos em resolução de 2 pixels/ponto. Tolerância observada de contorno: até 1 pixel (0,5 ponto PDF), considerando meia largura do traço.','- Exportação no PDF real 213M conserva tamanho da prancha, adiciona legenda A4, não preenche detalhe típico como instalação e permite backup/reimportação preservando vínculo, geometria e histórico.','- Worker mantém referência à vista em lease expirada e falha/retentativa de OCR.','',
'Os testes de saldo e geometria usam dados isolados/sintéticos para verificar regras; não homologam localizações nos desenhos reais. As nove posições de 212-F e a identidade de 210-N entre 202M/205M continuam como hipóteses visuais para o responsável revisar. Não foi medida precisão/vazamento de segmentação automática: esse recurso não é publicado.','',
'## OCR: benchmark inicial, sem aprovação automática','',
'Motor tesseract.js 7 / eng OEM1, comparando PSM7 e PSM11. Dois recortes de calibração de 200M (208-AB / 212-F); três recortes de avaliação de 208M/213M (212-F, 224-G, eixo 3-A). Recorte vazio de título em 205M foi identificado e explicitamente excluído. Quatro orientações por recorte são variantes do mesmo exemplo, não observações independentes.','',
'Os dois modos recuperaram os códigos amostrados quando as leituras das quatro orientações são reunidas. O reconhecimento direto de orientações incorretas é fraco e aparece nas métricas. A estratégia corrige orientação por renderização/transformação, conserva origem e gera somente candidatos. PSM11 selecionado por empate na calibração e adequação a texto esparso; parâmetro experimental, sem garantia estatística. Métricas brutas em reports/evidence/ocr/metrics.json.','',
'## Benchmark e verificação visual','',
f'Inspeção total: {result["benchmark"]["inspection_seconds_total"]:.2f} s; máximo por arquivo: {result["benchmark"]["inspection_seconds_max"]:.2f} s. Máximo RSS amostrado no fim do arquivo: {result["benchmark"]["rss_mb_max_sampled"]:.1f} MB (não é pico isolado). Valores são desta máquina/runtime, com pdfplumber + PDFium e duas resoluções. Worker tem limite de 120 s e 1 GB de RSS amostrado do processo e filhos; renderização até 24 milhões de pixels.',
'',
f'Primeira navegação até PDF completo no teste do navegador: {browser.get("navigation_complete_pdf_ms",browser.get("navigation_ms",0))/1000:.2f} s. Este número inclui interface, busca do original e renderização da primeira prancha; não é SLA. Não foram feitos ensaios de carga multiusuário ou distribuição de percentis de latência.','',
'HTMLs foram abertos por arquivo local, com e sem conexão. Kodchasan/Open Sans e imagens estão incorporadas; nenhuma API, CDN ou PDF.js externa é necessária. Tela desktop/mobile e primeira página A4 foram inspecionadas visualmente. Estilos imprimem sem header sticky/controles e com break-inside:avoid. PDFs A4 de QA são gerenciais; as pranchas técnicas no ZIP mantêm o formato original.','',
'## Portas ainda abertas','',
'Homologação linha a linha da BOM; reconciliação de peso; localização/identidade das unidades com decisões aprovadas; corpus rotulado mais amplo e métricas de falsas associações; ensaio real PostgreSQL; operação concorrente sob carga; critérios de risco e de latência aprovados. Não estão liberados aprovação automática, segmentação automática, migração automática de geometrias, percentuais parciais por unidade ou avanço ponderado por peso. Etapas são configuráveis com dependências; não se somam sem configuração aprovada.','',
'Entrega funcional: diagnóstico, catálogo/vistas/medição/pintura manual persistidos, revisão assistida experimental, auditoria, snapshot e exportação/reimportação. O projeto inicial continua sem medições reais ou vínculos físicos aprovados.','']
if workflow.exists():
    lines+=['## Fluxo manual pela interface (dados isolados)','',
            'Teste Chromium com o PDF real 677-208M e banco separado em tmp/ui-workflow: cadastro do código e configuração da etapa, delimitação de vista por quatro cliques, pintura retangular, associação manual ao tipo sem unidade, medição agregada 3/9, desfazer/refazer sem alterar medição, giro de 90° e zoom de 55%, salvar/reabrir conservando exatamente os pontos PDF. Nenhuma unidade foi criada e nenhum dado do projeto real foi alterado. Sem erros JavaScript.','',
            'O ensaio encontrou e corrigiu a validação HTML de largura (step incompatível com o padrão 6 pt) e verificou a entrada de vértices por PointerEvent. Evidência: reports/qa/ui-workflow-validation.json e fluxo-manual-rotacionado.png.','']
(ROOT/'VALIDACAO.md').write_text('\n'.join(lines),encoding='utf-8')
print('Validation report written. 45 passed, 1 skipped; all 14 real PDFs.')
